### ISSUE TITLE
npm install [ERROR] 

### ISSUE THREAD

**Issue by yagancadorin** [zoom/sample-app-ionic#1]
When I execute the command "npm install", the following error appears:

npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../Zoom" as it does not contain a package.json file.

In package-json file:

"cordova.plugin.zoom": "file:../../Zoom"

What can I do?

**Comment by carsonzoom** [comment]
Hi yagancadorin,
Thanks for mention this. I have removed the relative path and updated the package.json file. Please try again and let me know if you have any other questions.

Since the Ionic team have not updated their latest release to npm, please download the latest ionic-native from their repo: https://github.com/ionic-team/ionic-native.

Thanks!
